language: scala
scala:
  - 2.10.4
  - 2.11.0

jdk:
  - openjdk7

notifications:
  email:
    - otrimegistro@gmail.com

before_script:
  - sudo /etc/init.d/aerospike start
  - sudo /etc/init.d/aerospike status

script: sbt ++$TRAVIS_SCALA_VERSION test

after_script:
  - sudo /etc/init.d/aerospike stop

after_success: >
  test $TRAVIS_BRANCH == master &&
  test $PUBLISH_ENABLED == true &&
  test $TRAVIS_PULL_REQUEST == false &&
  test sbt ++$TRAVIS_SCALA_VERSION publish

after_failure:
  - sudo cat /etc/aerospike/aerospike.conf
  - sudo cat /var/log/aerospike/aerospike.log

env:
  global:
    - PUBLISH_ENABLED=false
    - secure: |-
        Nph15Ef9UWS/Wnpiivd/1xWjxyeVTrvsPdAeFP85yJLOvZnxTLarM9QS31YghNDnLrV0oOpe65BYNKpYb26zCA
        zKEQQrBBIftQUTvgnqvdKsHre+/MLJE9cdWeiWTldSSuZAAwQIt9ikqnGrfsAp3ltldh3CARGyKOBh4G59qIo=
    - secure: |-
        I3QQPyVIPwHuxbDhIke51iZ4z6VnEFoRmElPcY7DpHbX84jUDDLRwincdzoTn6oyA2bpjdlgKIYqNnd1OYh90w
        4lo6C30ORQelQG9wMI0jxLbRZ7zsyMFFIqVbiFt9KM62GGPRPXhH1nO2SqIw962NOE+skgJnXiiibH41/SkVg=

before_install:
  - V="3.2.8"
  - AEROSPIKE_SERVER="aerospike-community-server-${V}-ubuntu12.04"
  - wget http://www.aerospike.com/community_downloads/${V}/${AEROSPIKE_SERVER}.tgz
  - tar xvf ${AEROSPIKE_SERVER}.tgz
  - sudo dpkg -i ${AEROSPIKE_SERVER}/aerospike-community-server*
  - rm -rf ${AEROSPIKE_SERVER}*
  - sudo sed -i s/"pidfile \/var\/run\/aerospike\/asd.pid"/"pidfile \/var\/run\/asd.pid"/ /etc/aerospike/aerospike.conf
  - sudo sed -i '/reuse-address/a network-interface-name venet0' /etc/aerospike/aerospike.conf
